"""ASCII Polygon File Format (PLY) export for triangle meshes."""

from pathlib import Path
from typing import TextIO, Union

from .mesh import TriangleMesh


PathLike = Union[str, Path]


def _number(value: float) -> str:
    return "0" if value == 0.0 else format(value, ".17g")


def write_ply(mesh: TriangleMesh, destination: PathLike, include_normals: bool = True) -> None:
    """Write *mesh* as an ASCII PLY file."""

    with Path(destination).open("w", encoding="ascii", newline="\n") as stream:
        write_ply_stream(mesh, stream, include_normals)


def write_ply_stream(
    mesh: TriangleMesh, stream: TextIO, include_normals: bool = True
) -> None:
    """Write ASCII PLY text to an open stream."""

    stream.write("ply\nformat ascii 1.0\n")
    stream.write("comment generated by NatureGenerator\n")
    stream.write("element vertex {}\n".format(len(mesh.vertices)))
    stream.write("property double x\nproperty double y\nproperty double z\n")
    if include_normals:
        stream.write("property double nx\nproperty double ny\nproperty double nz\n")
    stream.write("element face {}\n".format(len(mesh.faces)))
    stream.write("property list uchar int vertex_indices\nend_header\n")

    normals = mesh.vertex_normals() if include_normals else ()
    for index, vertex in enumerate(mesh.vertices):
        values = vertex + normals[index] if include_normals else vertex
        stream.write("{}\n".format(" ".join(map(_number, values))))
    for face in mesh.faces:
        stream.write("3 {} {} {}\n".format(*face))
